import { readFile, writeFile } from "node:fs/promises";
import { seoPages, siteURL, pagePath } from "../js/seo.js";
import { start, end, metadata, renderPage } from "./seo-render.js";
const root = new URL("../", import.meta.url);
const check = process.argv.includes("--check");
async function output(path, content) {
  const url = new URL(path, root);
  if (check) {
    if ((await readFile(url, "utf8").catch(() => "")) !== content)
      throw new Error(`${path} is stale; run npm run seo:generate`);
  } else await writeFile(url, content);
}
const html = await readFile(new URL("index.html", root), "utf8");
await output("index.html", renderPage(html, "home"));
for (const page of Object.keys(seoPages).filter((key) => key !== "home")) {
  await output(
    `${page}.html`,
    `---\npermalink: ${pagePath(page)}\n---\n{% comment %}Generated by npm run seo:generate. Edit js/seo.js.{% endcomment %}\n{% capture app %}{% include_relative index.html %}{% endcapture %}\n{{ app | split: '${start}' | first }}\n${start}\n${metadata(page)}\n${end}\n{{ app | split: '${end}' | last | replace: 'class="page active" id="page-home"', 'class="page" id="page-home"' | replace: 'class="page" id="page-${page}"', 'class="page active" id="page-${page}"' }}\n`,
  );
}
await output(
  "sitemap.xml",
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${Object.entries(
    seoPages,
  )
    .filter(([, data]) => !data.noindex)
    .map(([page]) => `  <url><loc>${siteURL + pagePath(page)}</loc></url>`)
    .join("\n")}\n</urlset>\n`,
);
await output(
  "robots.txt",
  `User-agent: *\nAllow: /\n\nSitemap: ${siteURL}/sitemap.xml\n`,
);
